# Generated by Django 3.2 on 2023-01-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_app', '0002_initial'),
        ('advance_deposit', '0002_initial'),
        ('item', '0002_initial'),
        ('user_group', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0002_initial'),
        ('customer', '0003_initial'),
        ('sale', '0001_initial'),
        ('customer_order', '0002_initial'),
        ('warehouse_location', '0001_initial'),
        ('party_payment', '0001_initial'),
        ('chalan', '0002_initial'),
        ('supplier', '0001_initial'),
        ('asset', '0002_initial'),
        ('credit_management', '0002_initial'),
        ('item_serialization', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logordermaster',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logordermaster',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='logordermaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='logordermaster',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logorderdetail',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item'),
        ),
        migrations.AddField(
            model_name='logorderdetail',
            name='item_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='logorderdetail',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_order.ordermaster'),
        ),
        migrations.AddField(
            model_name='logorderdetail',
            name='picked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logorderdetail',
            name='purchase_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasedetail'),
        ),
        migrations.AddField(
            model_name='loglocation',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse_location.location'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='generic_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.genericname'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='item_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.manufacturer'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' blank=True, null= True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.unit'),
        ),
        migrations.AddField(
            model_name='logdistrict',
            name='province',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Fk Province', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.province'),
        ),
        migrations.AddField(
            model_name='logcustompermission',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='null=Ture, blank=True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user_group.permissioncategory'),
        ),
        migrations.AddField(
            model_name='logcustomer',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='blank= True and null= True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.country'),
        ),
        migrations.AddField(
            model_name='logcustomer',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='logcreditpaymentdetail',
            name='credit_clearance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='credit_management.creditclearance'),
        ),
        migrations.AddField(
            model_name='logcreditpaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logcreditclearance',
            name='ref_credit_clearance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='credit_management.creditclearance'),
        ),
        migrations.AddField(
            model_name='logcreditclearance',
            name='sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
        migrations.AddField(
            model_name='logchalanmaster',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='logchalanmaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='logchalanmaster',
            name='ref_chalan_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chalan.chalanmaster'),
        ),
        migrations.AddField(
            model_name='logchalanmaster',
            name='ref_order_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_order.ordermaster'),
        ),
        migrations.AddField(
            model_name='logchalandetail',
            name='chalan_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chalan.chalanmaster'),
        ),
        migrations.AddField(
            model_name='logchalandetail',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item'),
        ),
        migrations.AddField(
            model_name='logchalandetail',
            name='item_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='logchalandetail',
            name='ref_chalan_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chalan.chalandetail'),
        ),
        migrations.AddField(
            model_name='logchalandetail',
            name='ref_order_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_order.orderdetail'),
        ),
        migrations.AddField(
            model_name='logchalandetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasedetail'),
        ),
        migrations.AddField(
            model_name='logbasicpartypaymentdetail',
            name='basic_party_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='party_payment.basicpartypayment'),
        ),
        migrations.AddField(
            model_name='logbasicpartypaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logbasicpartypayment',
            name='fiscal_session_ad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.fiscalsessionad'),
        ),
        migrations.AddField(
            model_name='logbasicpartypayment',
            name='fiscal_session_bs',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.fiscalsessionbs'),
        ),
        migrations.AddField(
            model_name='logbasicpartypayment',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='logbankdeposit',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.bank'),
        ),
        migrations.AddField(
            model_name='logassettransfer',
            name='asset_dispatch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetdispatch'),
        ),
        migrations.AddField(
            model_name='logassetsubcategory',
            name='asset_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetcategory'),
        ),
        migrations.AddField(
            model_name='logassetservice',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetlist'),
        ),
        migrations.AddField(
            model_name='logassetmaintenance',
            name='asset_dispatch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetdispatch'),
        ),
        migrations.AddField(
            model_name='logassetmaintenance',
            name='issued_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logassetlist',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.asset'),
        ),
        migrations.AddField(
            model_name='logassetlist',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse_location.location'),
        ),
        migrations.AddField(
            model_name='logassetlist',
            name='packing_type_detail_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item_serialization.packingtypedetailcode'),
        ),
        migrations.AddField(
            model_name='logassetissue',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetlist'),
        ),
        migrations.AddField(
            model_name='logassetissue',
            name='issued_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logassetissue',
            name='return_received_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logassetdispatchdetail',
            name='asset_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetlist'),
        ),
        migrations.AddField(
            model_name='logassetdispatchdetail',
            name='asset_dispatch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetdispatch'),
        ),
        migrations.AddField(
            model_name='logassetdispatchdetail',
            name='picked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logassetdispatchdetail',
            name='ref_dispatch_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetdispatchdetail'),
        ),
        migrations.AddField(
            model_name='logassetdispatch',
            name='dispatch_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='dispatch by user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logassetdispatch',
            name='dispatch_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='dispatch to user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logassetdispatch',
            name='ref_dispatch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetdispatch'),
        ),
        migrations.AddField(
            model_name='logassetdispatch',
            name='returned_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Returned by user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logasset',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetcategory'),
        ),
        migrations.AddField(
            model_name='logasset',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item'),
        ),
        migrations.AddField(
            model_name='logasset',
            name='sub_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetsubcategory'),
        ),
        migrations.AddField(
            model_name='logadvanceddepositpaymentdetail',
            name='advanced_deposit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='advance_deposit.advanceddeposit'),
        ),
        migrations.AddField(
            model_name='logadvanceddepositpaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logadvanceddeposit',
            name='order_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_order.ordermaster'),
        ),
        migrations.AddField(
            model_name='logadvanceddeposit',
            name='sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
    ]
