# Generated by Django 3.2 on 2023-01-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20230104_1041'),
        ('log_app', '0006_auto_20230104_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='loguser',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='department.department'),
        ),
    ]
