# Generated by Django 3.2 on 2023-01-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0008_logdepartment_allow_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchasemaster',
            name='department_transfer_master_transfer_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='logpurchasemaster',
            name='purchase_type',
            field=models.PositiveIntegerField(choices=[(1, 'PURCHASE'), (2, 'RETURN'), (3, 'OPENING-STOCK'), (4, 'STOCK-ADDITION'), (5, 'STOCK-DEPARTMENT')], help_text='Purchase type like 1= Purchase, 2 = Return, 3 = Opening stock, 4 = stock-addition, 5 = stock-subtraction'),
        ),
    ]
