# Generated by Django 3.2 on 2023-01-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_allow_sales'),
        ('log_app', '0009_auto_20230105_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchaseordermaster',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='department.department'),
        ),
    ]
