# Generated by Django 3.2 on 2023-01-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0010_logpurchaseordermaster_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loguser',
            name='department',
        ),
    ]
