# Generated by Django 3.2 on 2023-01-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0013_alter_logpurchasemaster_purchase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchasedetail',
            name='ref_department_transfer_detail',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
