# Generated by Django 3.2 on 2023-01-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0014_logpurchasedetail_ref_department_transfer_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logpurchasemaster',
            name='department_transfer_master_transfer_no',
        ),
        migrations.AddField(
            model_name='logpurchasemaster',
            name='ref_department_transfer_master',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
