# Generated by Django 3.2 on 2023-01-04 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20230104_1041'),
        ('warehouse_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='department.department'),
            preserve_default=False,
        ),
    ]
