# Generated by Django 3.2 on 2023-01-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_serializable',
            field=models.BooleanField(default=True),
        ),
    ]
