# Generated by Django 3.2 on 2023-01-02 07:29

import django.core.validators
from django.db import migrations, models
import src.core_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalChargeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='Additional Charge type name must be max 50 characters, unique=True', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True, help_text='default=True')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other')], default='NA', help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App')], default='NA', help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('deposit_date_ad', models.DateTimeField()),
                ('deposit_date_bs', models.CharField(blank=True, max_length=10)),
                ('deposit_by', models.CharField(help_text='max length can be 50 characters', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='User can input value upto 99999999.99', max_digits=12)),
                ('remarks', models.CharField(blank=True, help_text='max length can be 50 characters and blank=True', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='Name of the country can have max upto 50 characters, unique=True', max_length=50, unique=True)),
                ('country_code', models.CharField(blank=True, help_text='country_code can be have max upto 5 characters and null=True, blank=True', max_length=5, null=True)),
                ('phone_code', models.CharField(blank=True, help_text='phone_code can be have max upto 5 characters and null=True, blank=True', max_length=5, null=True)),
                ('flag_image', models.ImageField(blank=True, help_text='Image can be max of 2 MB size, blank=True', upload_to='flag_image', validators=[src.core_app.models.validate_image])),
                ('active', models.BooleanField(default=True, help_text='By default=true')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='currency_name can be have max upto 50 characters and null=True, blank=True', max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, help_text='currency_symbol can be have max upto 3 characters and null=True, blank=True', max_length=3, null=True)),
                ('code', models.CharField(blank=True, help_text='currency_name can be have max upto 3 characters and null=True, blank=True', max_length=3, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='Discount scheme name must be max 50 characters, uqique=True', max_length=50, unique=True)),
                ('editable', models.BooleanField(default=False, help_text='default=False')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount Rate default=0.00 max upto 100.00', max_digits=5)),
                ('active', models.BooleanField(default=True, help_text='by default=True')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='District name can be max. of 50 characters and unique=True', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True, help_text='by default=True')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalSessionAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('session_full', models.CharField(blank=True, help_text='Should be unique and must contain 9 characters', max_length=9, unique=True)),
                ('session_short', models.CharField(blank=True, help_text='Should be unique and must contain 5 characters', max_length=5, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalSessionBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('session_full', models.CharField(blank=True, help_text='Should be unique and must contain 9 characters', max_length=9, unique=True)),
                ('session_short', models.CharField(blank=True, help_text='Should be unique and must contain 5 characters', max_length=5, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('customer_seq_type', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS'), (3, 'SEQUENTIAL')], default=2, help_text='where 1=AD,2=BS,3=SEQUENTIAL  and default=2')),
                ('fiscal_session_type', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS')], default=2, help_text='Where 1 = AD , 2 = BS and default=2')),
                ('calendar_system', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS')], default=2, help_text='Where 1 = AD , 2 = BS and default=2')),
                ('enable_print', models.BooleanField(default=True)),
                ('print_preview', models.BooleanField(default=True)),
                ('billing_time_restriction', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('first_day_of_week', models.PositiveIntegerField(choices=[(1, 'SUNDAY'), (2, 'MONDAY'), (3, 'TUESDAY'), (4, 'WEDNESDAY'), (5, 'THURSDAY'), (6, 'FRIDAY'), (7, 'SATURDAY')], default=1, help_text='where 1 = Sunday ---- 7 =Saturday')),
                ('tax_system', models.PositiveIntegerField(choices=[(1, 'VAT'), (2, 'PAN')], default=1, help_text='where 1=VAT, 2=PAN')),
                ('round_off_limit', models.PositiveIntegerField(default=2)),
                ('round_off_purchase', models.BooleanField(default=True)),
                ('round_off_sale', models.BooleanField(default=True)),
                ('item_expiry_date_sale_threshold', models.PositiveIntegerField(default=30)),
                ('tax_applicable', models.BooleanField(default=True)),
                ('tax_rate', models.FloatField(default=0.0, help_text='Tax rate', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='Organization name should be maximum of 100 characters', max_length=100, unique=True)),
                ('address', models.CharField(blank=True, help_text='Organization name should be maximum of 100 characters', max_length=100, unique=True)),
                ('phone_no_1', models.CharField(blank=True, help_text='Phone no should be maximum of 15 characters', max_length=15, unique=True)),
                ('phone_no_2', models.CharField(blank=True, help_text='Phone no should be maximum of 15 characters', max_length=15)),
                ('mobile_no', models.CharField(blank=True, help_text='Mobile no should be maximum of 15 characters', max_length=15, unique=True)),
                ('pan_no', models.CharField(blank=True, help_text='PAN no. should be maximum of 15 characters', max_length=15, unique=True)),
                ('owner_name', models.CharField(blank=True, help_text='Owner name should be maximum of 50 characters', max_length=50, unique=True)),
                ('email', models.CharField(blank=True, help_text='Email Id. should be maximum of 70 characters', max_length=70, unique=True)),
                ('website_url', models.CharField(blank=True, help_text='Website address should be maximum of 50 characters', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, default='default_images/soori.png', upload_to='organization_setup/logo', validators=[src.core_app.models.validate_organization_setup_images, django.core.validators.FileExtensionValidator(allowed_extensions=['png'])])),
                ('favicon', models.ImageField(blank=True, default='default_images/favicon.ico', null=True, upload_to='organization_setup/favicon', validators=[src.core_app.models.validate_organization_setup_images])),
                ('stamp', models.ImageField(blank=True, default='default_images/stamp.png', help_text='stamp image of organization', upload_to='organization_setup/stamp', validators=[src.core_app.models.validate_organization_setup_images])),
                ('signature', models.ImageField(blank=True, default='default_images/signature.png', help_text='signature image of organization owner', null=True, upload_to='organization_setup/signature', validators=[src.core_app.models.validate_organization_setup_images])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('type', models.PositiveIntegerField(choices=[(1, 'CASH'), (2, 'BANK'), (3, 'WALLET')], default=1)),
                ('name', models.CharField(help_text='Name can have max upto 15 character, unique=True', max_length=15, unique=True)),
                ('active', models.BooleanField(default=0, help_text='by default=0')),
                ('remarks', models.CharField(blank=True, help_text='remarks can have max upto 50 character, blank=True', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='Province name can be max. of 50 characters and unique=True', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True, help_text='by default=True')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='Name can have max of 30 characaters and must be Unique', max_length=30, unique=True)),
                ('code', models.CharField(blank=True, help_text='Item code should be max. of 10 characters', max_length=7, unique=True)),
                ('active', models.BooleanField(default=True, help_text='By default active=True')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='Name can have max of 20 characaters and must be unique', max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default=0.0', max_digits=5)),
                ('display_order', models.IntegerField(default=0, help_text='Display order for ordering, default=0')),
                ('active', models.BooleanField(default=True, help_text='By default active=True')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
