# Generated by Django 3.2 on 2023-01-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230106_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='departments',
        ),
    ]
