"""
Django settings for ims project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

# Add allowed hosts separated by space in env file
# example: ALLOWED_HOSTS=".example.com example.com"
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS")
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS")

# env.str('CORS_ALLOWED_ORIGINS', multiline=True)
# env.list("CORS_ALLOWED_ORIGINS")
# CORS_ALLOWED_ORIGINS=[env.list('CORS_ALLOWED_ORIGINS')]]

# Application definition
ims_apps = [
    'src.user',
    'src.api',
    'src.core_app',
    'src.item',
    'src.supplier',
    'src.purchase',
    'src.customer',
    'src.sale',
    'src.financial_report',
    'src.customer_order',
    'src.credit_management',
    'src.party_payment',
    'src.dashboard',
    'src.stock_adjustment',
    'src.user_group',
    'src.advance_deposit',
    'src.opening_stock',
    'log_app',
    'tenant',
    'src.ird_report',
    'src.warehouse_location',
    'src.item_serialization',
    'src.asset',
    'src.audit',
    'src.chalan',
    'src.stock_analysis',
    'src.notification',
    'src.quotation',
    'src.central_report',
    'src.transfer',
    'src.repair',
    'src.account',
    'src.department',
    'src.department_transfer',
    'src.ppb'

]
THIRD_PARTY_APPS = [
    'corsheaders',
    'django_filters',
    'rest_framework_simplejwt.token_blacklist',
    "rest_framework",
    "drf_yasg",
    'django_rest_resetpassword',
    # 'debug_toolbar',
    'simple_history',
    'mptt',
    'channels'
]
INSTALLED_APPS = [
                     'django.contrib.admin',
                     'django.contrib.auth',
                     'django.contrib.contenttypes',
                     'django.contrib.sessions',
                     'django.contrib.messages',
                     'django.contrib.staticfiles',
                 ] + ims_apps + THIRD_PARTY_APPS

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # cors headers middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "tenant.middlewares.TenantMiddleware",  # custom middleware for tenants
    # simple-history-middleware to track user
    'simple_history.middleware.HistoryRequestMiddleware',
    # 'src.notification.get_request.RequestMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',# debug toolbar
    # 'ipinfo_django.middleware.IPinfo', #ipaddress
]

ROOT_URLCONF = 'ims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'ims.wsgi.application'
ASGI_APPLICATION = 'ims.asgi.application'
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env("DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'HOST': env("DB_HOST"),
        'PORT': env("DB_PORT"),
    },
    'log_db': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env("HISTORY_DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'HOST': env("DB_HOST"),
        'PORT': env("DB_PORT"),
    }
}
DATABASE_ROUTERS = ["tenant.router.HistoryRouter"]
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'user.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# REST FRAMEWORK config
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'src.custom_lib.pagination.CustomLimitOffsetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        "custom_jwt_authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),

    # apply permission class to all purchase_order_view Classes
    "DEFAULT_PERMISSION_CLASSES": [
        # 'rest_framework.permissions.AllowAny',
        "rest_framework.permissions.IsAuthenticated",
        # "src.custom_lib.permissions.model_permissions.CustomDjangoModelPermissions",
    ],
    "DEFAULT_PARSER_CLASSES": [
        # nested parser are just default DRF parsers with extended
        # functionalities to support nested

        'drf_nested_forms.parsers.NestedMultiPartParser',
        'drf_nested_forms.parsers.NestedJSONParser',
        'rest_framework.parsers.FormParser',

        # so this settings will work in respective of a nested request
        # or not
    ]
    # 'DEFAULT_RENDERER_CLASSES': (
    #         'rest_framework.renderers.JSONRenderer',
    #         'rest_framework.renderers.BrowsableAPIRenderer',
    #         'drf_renderer_xlsx.renderers.XLSXRenderer',
    #     ),
}
# json web token configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}
# upload size for image files in bytes ( approx 2 MB)
MAX_UPLOAD_SIZE = 2097152

# remove slash from end of api urls
APPEND_SLASH = False

# for images
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'dipee.info@gmail.com'
SERVER_EMAIL = 'dipee.info@gmail.com'
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "dipee.info@gmail.com"
EMAIL_HOST_PASSWORD = "voqhmmpuaqidgxwg"
EMAIL_PORT = 587

# nested form parser settings
NESTED_FORM_PARSER = {
    'OPTIONS': {
        'allow_empty': True,
        'allow_blank': True
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            'hosts': [
                f'redis://127.0.0.1:6379/{env("REDIS_SERVER_DB")}',
            ],
        },
    },
}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
