# Generated by Django 3.2 on 2023-01-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0002_initial'),
        ('purchase', '0002_initial'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferordermaster',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferorderdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferorderdetail',
            name='item',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='item.item'),
        ),
        migrations.AddField(
            model_name='transferorderdetail',
            name='item_category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='transferorderdetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_order_purchase_details', to='purchase.purchasedetail'),
        ),
        migrations.AddField(
            model_name='transferorderdetail',
            name='transfer_order_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_order_details', to='transfer.transferordermaster'),
        ),
        migrations.AddField(
            model_name='transfermaster',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfermaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='transfermaster',
            name='fiscal_session_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.fiscalsessionad'),
        ),
        migrations.AddField(
            model_name='transfermaster',
            name='fiscal_session_bs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.fiscalsessionbs'),
        ),
        migrations.AddField(
            model_name='transfermaster',
            name='ref_transfer_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transfer.transfermaster'),
        ),
        migrations.AddField(
            model_name='transfermaster',
            name='ref_transfer_order_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transfer.transferordermaster'),
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='item',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='item.item'),
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='item_category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_purchase_details', to='purchase.purchasedetail'),
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='ref_transfer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transfer.transferdetail'),
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='ref_transfer_order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transfer.transferorderdetail'),
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='transfer_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_details', to='transfer.transfermaster'),
        ),
    ]
