# Generated by Django 3.2 on 2023-01-09 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0005_purchaseordermaster_department'),
        ('item', '0003_item_is_serializable'),
        ('department', '0003_department_allow_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPBDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_ppb', to='item.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PPBMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('Name of the PPB item, can be of max 100 characters', models.CharField(max_length=100, unique=True)),
                ('ppb_no', models.CharField(help_text='PPB no for the item, can be of max 15 characters', max_length=15, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, help_text='remarks for ppb main', max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_item_ppb', to='item.item')),
            ],
            options={
                'verbose_name': 'PPBMain',
                'verbose_name_plural': 'PPBMains',
            },
        ),
        migrations.CreateModel(
            name='TaskMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('expected_output_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('task_no', models.CharField(max_length=20, unique=True)),
                ('remarks', models.CharField(blank=True, help_text='remarks for task main', max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_department', to='department.department')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_item_task', to='item.item')),
                ('ppb_main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppb_task', to='ppb.ppbmain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_output_item', to='item.item')),
                ('packing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.packingtype')),
                ('packing_type_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.packingtypedetail')),
                ('task_main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_output', to='ppb.taskmain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_details_item', to='item.item')),
                ('ppb_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_details_ppb', to='ppb.ppbdetail')),
                ('purchase_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_detail_purchase', to='purchase.purchasedetail')),
                ('task_main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_details', to='ppb.taskmain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ppbdetail',
            name='ppb_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppb_details', to='ppb.ppbmain'),
        ),
    ]
