# Generated by Django 3.2 on 2023-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Cancel a task detail'),
        ),
        migrations.AddField(
            model_name='taskmain',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve Task by Permitted User'),
        ),
        migrations.AddField(
            model_name='taskmain',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Cancel entire task'),
        ),
    ]
