# Generated by Django 3.2 on 2023-01-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppb', '0002_auto_20230110_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppbmain',
            name='Name of the PPB item, can be of max 100 characters',
        ),
        migrations.AddField(
            model_name='ppbmain',
            name='name',
            field=models.CharField(default=None, help_text='Name of the PPB item, can be of max 100 characters', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
