# Generated by Django 3.2 on 2023-01-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppb', '0003_auto_20230110_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='picked',
            field=models.BooleanField(default=False, help_text='picked boolean for task detail, defaults to false'),
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='picked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='task_details_picked', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmain',
            name='approved_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='task_main_approved', to='user.user'),
            preserve_default=False,
        ),
    ]
