# Generated by Django 3.2 on 2023-01-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppb', '0004_auto_20230110_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppbmain',
            name='ppb_no',
            field=models.CharField(help_text='PPB no for the item, can be of max 15 characters', max_length=20, unique=True),
        ),
    ]
