# Generated by Django 3.2 on 2023-01-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chalan', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_order', '0001_initial'),
        ('customer', '0002_initial'),
        ('item', '0001_initial'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalanmaster',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chalanmaster',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='chalanmaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='chalanmaster',
            name='ref_chalan_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chalan.chalanmaster'),
        ),
        migrations.AddField(
            model_name='chalanmaster',
            name='ref_order_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_order.ordermaster'),
        ),
        migrations.AddField(
            model_name='chalandetail',
            name='chalan_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chalan_details', to='chalan.chalanmaster'),
        ),
        migrations.AddField(
            model_name='chalandetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chalandetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item'),
        ),
        migrations.AddField(
            model_name='chalandetail',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='chalandetail',
            name='ref_chalan_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chalan.chalandetail'),
        ),
        migrations.AddField(
            model_name='chalandetail',
            name='ref_order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_order.orderdetail'),
        ),
        migrations.AddField(
            model_name='chalandetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchasedetail'),
        ),
    ]
