# Generated by Django 3.2 on 2023-01-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_transfer', '0002_alter_departmenttransfermaster_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttransferdetail',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmenttransfermaster',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmenttransfermaster',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmenttransfermaster',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
