# Generated by Django 3.2 on 2023-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_transfer', '0003_auto_20230106_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenttransferdetail',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='departmenttransfermaster',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='departmenttransferdetail',
            name='expiry_date_ad',
            field=models.DateField(blank=True, help_text='Expiry Date AD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='departmenttransferdetail',
            name='expiry_date_bs',
            field=models.CharField(blank=True, help_text='Expiry Date BS', max_length=10),
        ),
    ]
