# Generated by Django 3.2 on 2023-01-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_transfer', '0004_auto_20230108_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenttransferdetail',
            name='sale_cost',
        ),
    ]
