# Generated by Django 3.2 on 2023-01-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_transfer', '0005_remove_departmenttransferdetail_sale_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenttransferdetail',
            name='batch_no',
        ),
    ]
