# Generated by Django 3.2 on 2023-01-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department_transfer', '0007_remove_departmenttransfermaster_ref_purchase_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttransferdetail',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmenttransferdetail',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_transfer_details_picked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmenttransfermaster',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_transfer_master_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmenttransfermaster',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_transfer_master_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
