# Generated by Django 3.2 on 2023-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_transfer', '0008_auto_20230109_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttransfermaster',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
