# Generated by Django 3.2 on 2023-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_transfer', '0010_auto_20230109_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttransferdetail',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='departmenttransfermaster',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
