# Generated by Django 3.2 on 2023-01-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_order', '0001_initial'),
        ('chalan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingTypeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('code', models.CharField(help_text='max-20', max_length=20, verbose_name='Packing Type Serial No')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackingTypeDetailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('code', models.CharField(help_text='max-20', max_length=20, verbose_name='Packing Type Detail Serail No')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RfidTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('code', models.CharField(help_text='max-20', max_length=255, unique=True, verbose_name='Rfid Tag Key Code')),
                ('last_seen_dt', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalePackingTypeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalan_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chalan_packing_types', to='chalan.chalandetail', verbose_name='Chalan Detail')),
                ('customer_order_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_packing_types', to='customer_order.orderdetail', verbose_name='Customer order detail')),
                ('packing_type_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_type_code_of_sale', to='item_serialization.packingtypecode', verbose_name='sale packing type code')),
                ('ref_sale_packing_type_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_serialization.salepackingtypecode')),
            ],
        ),
        migrations.CreateModel(
            name='SalePackingTypeDetailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_type_detail_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_type_detail_code_of_sale', to='item_serialization.packingtypedetailcode')),
                ('ref_sale_packing_type_detail_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_serialization.salepackingtypedetailcode')),
                ('sale_packing_type_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_packing_type_detail_code', to='item_serialization.salepackingtypecode')),
            ],
        ),
    ]
