# Generated by Django 3.2 on 2023-01-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_serialization', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepackingtypecode',
            name='sale_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_packing_type_code', to='sale.saledetail', verbose_name='Sale Detail'),
        ),
    ]
