# Generated by Django 3.2 on 2023-01-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfer', '0001_initial'),
        ('item_serialization', '0002_salepackingtypecode_sale_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepackingtypecode',
            name='transfer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_packing_types', to='transfer.transferdetail', verbose_name='Transfer Detail'),
        ),
    ]
