# Generated by Django 3.2 on 2023-01-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_serialization', '0003_salepackingtypecode_transfer_detail'),
        ('warehouse_location', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidtag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='pack_type_detail_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rfid_tag_codes', to='item_serialization.packingtypedetailcode', verbose_name='Rfid Tag Code'),
        ),
        migrations.AddField(
            model_name='packingtypedetailcode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packingtypedetailcode',
            name='pack_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_type_detail_codes', to='item_serialization.packingtypecode', verbose_name='Packing Type Code'),
        ),
        migrations.AddField(
            model_name='packingtypedetailcode',
            name='ref_packing_type_detail_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_serialization.packingtypedetailcode'),
        ),
        migrations.AddField(
            model_name='packingtypecode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packingtypecode',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_pack_codes', to='warehouse_location.location', verbose_name='Pack Type Location'),
        ),
        migrations.AddField(
            model_name='packingtypecode',
            name='purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pu_pack_type_codes', to='purchase.purchasedetail', verbose_name='Purchase Detail'),
        ),
        migrations.AddField(
            model_name='packingtypecode',
            name='purchase_order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_pack_type_codes', to='purchase.purchaseorderdetail', verbose_name='Purchase Order Detail'),
        ),
        migrations.AddField(
            model_name='packingtypecode',
            name='ref_packing_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_serialization.packingtypecode'),
        ),
    ]
