# Generated by Django 3.2 on 2023-01-02 08:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingtypecode',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salepackingtypecode',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
