# Generated by Django 3.2 on 2023-01-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_transfer', '0002_alter_departmenttransfermaster_transfer_type'),
        ('item_serialization', '0005_auto_20230102_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepackingtypecode',
            name='department_transfer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_transfer_packing_types', to='department_transfer.departmenttransferdetail', verbose_name='Department Transfer Detail'),
        ),
    ]
