# Generated by Django 3.2 on 2023-01-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppb', '0001_initial'),
        ('item_serialization', '0006_salepackingtypecode_department_transfer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepackingtypecode',
            name='task_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_packing_type_codes', to='ppb.taskdetail'),
        ),
    ]
