# Generated by Django 3.2 on 2023-01-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0002_initial'),
        ('supplier', '0001_initial'),
        ('party_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partypaymentdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partypaymentdetail',
            name='party_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_payment_details', to='party_payment.partypayment'),
        ),
        migrations.AddField(
            model_name='partypaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='partypayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partypayment',
            name='purchase_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_payments', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='partypayment',
            name='ref_party_clearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='party_payment.partypayment'),
        ),
        migrations.AddField(
            model_name='basicpartypaymentdetail',
            name='basic_party_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basic_party_payment_details', to='party_payment.basicpartypayment'),
        ),
        migrations.AddField(
            model_name='basicpartypaymentdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicpartypaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='basicpartypayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicpartypayment',
            name='fiscal_session_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.fiscalsessionad'),
        ),
        migrations.AddField(
            model_name='basicpartypayment',
            name='fiscal_session_bs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.fiscalsessionbs'),
        ),
        migrations.AddField(
            model_name='basicpartypayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
    ]
