# Generated by Django 3.2 on 2023-01-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0002_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepaymentdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasepaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='purchasepaymentdetail',
            name='purchase_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='purchaseordermaster',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseordermaster',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency For Foreign exchange', null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.currency'),
        ),
        migrations.AddField(
            model_name='purchaseordermaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='purchaseordermaster',
            name='ref_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_purchase_order_master', to='purchase.purchaseordermaster'),
        ),
        migrations.AddField(
            model_name='purchaseordermaster',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier', on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderdocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='purchase.purchasedocumenttype'),
        ),
        migrations.AddField(
            model_name='purchaseorderdocument',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_documents', to='purchase.purchaseordermaster'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='packing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.packingtype'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='packing_type_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.packingtypedetail'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_details', to='purchase.purchaseordermaster'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='ref_purchase_order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_purchase_order_detail', to='purchase.purchaseorderdetail'),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='fiscal_session_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.fiscalsessionad'),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='fiscal_session_bs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.fiscalsessionbs'),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='ref_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='ref_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaseordermaster'),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier null=True', null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='purchasedocumenttype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='purchase_document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='purchase.purchasedocumenttype'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='purchase_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_documents', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='packing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.packingtype'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='packing_type_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.packingtypedetail'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_ref_purchase_detail', to='purchase.purchasedetail'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='ref_purchase_order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaseorderdetail'),
        ),
        migrations.AddField(
            model_name='purchaseadditionalcharge',
            name='charge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.additionalchargetype'),
        ),
        migrations.AddField(
            model_name='purchaseadditionalcharge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseadditionalcharge',
            name='purchase_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_charges', to='purchase.purchasemaster'),
        ),
    ]
