# Generated by Django 3.2 on 2023-01-04 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20230104_1041'),
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemaster',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_stock', to='department.department'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='purchase_type',
            field=models.PositiveIntegerField(choices=[(1, 'PURCHASE'), (2, 'RETURN'), (3, 'OPENING-STOCK'), (4, 'STOCK-ADDITION'), (5, 'STOCK-SUBTRACTION'), (5, 'STOCK-DEPARTMENT')], help_text='Purchase type like 1= Purchase, 2 = Return, 3 = Opening stock, 4 = stock-addition, 5 = stock-subtraction'),
        ),
    ]
