# Generated by Django 3.2 on 2023-01-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name can have max of 50 characters', max_length=50)),
                ('created_date_ad', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date_bs', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name can have max of 50 characters', max_length=50)),
                ('code_name', models.CharField(help_text='Code Name can have max of 50 characters', max_length=50)),
                ('created_date_ad', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date_bs', models.CharField(max_length=10)),
                ('category', models.ForeignKey(blank=True, help_text='null=Ture, blank=True', null=True, on_delete=django.db.models.deletion.PROTECT, to='user_group.permissioncategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name can have max of 50 characters', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='by default=True')),
                ('created_date_ad', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date_bs', models.CharField(max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, help_text='blank=True', to='user_group.CustomPermission')),
            ],
        ),
    ]
