# Generated by Django 3.2 on 2023-01-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('customer', '0001_initial'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerissupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_is_customer', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(blank=True, help_text='blank= True and null= True', null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.country'),
        ),
    ]
